"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import PageHeader from "@/components/shared/PageHeader";
import SearchBar from "@/components/shared/SearchBar";
import DataTable, { type DataTableColumn } from "@/components/shared/DataTable";
import { StatusChip } from "@/components/shared/StatusChip";
import { listBills } from "@/lib/api/bills";
import type { Bill } from "@/lib/types";
import { formatINR, fullName } from "@/lib/utils";

export default function BillsInboxPage() {
  const router = useRouter();
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);

  const { data, isLoading } = useQuery({
    queryKey: ["bills", "inbox", search, page],
    queryFn: () => listBills({ search, page }),
  });

  const columns: DataTableColumn<Bill>[] = [
    { key: "id", header: "Bill No.", render: (r) => r.id.slice(0, 8).toUpperCase(), primary: true },
    { key: "orderNumber", header: "Order No.", render: (r) => r.order?.orderNumber ?? "—" },
    { key: "client", header: "Client", render: (r) => (r.client ? fullName(r.client) : "—") },
    { key: "seller", header: "Seller", render: (r) => (r.createdBySeller ? fullName(r.createdBySeller) : "—") },
    { key: "amount", header: "Amount", render: (r) => formatINR(r.amount), align: "right" },
  ];

  return (
    <div>
      <PageHeader title="Bills Inbox" description="Shared inbox — every seller's bills, ready for invoicing." />
      <SearchBar value={search} onChange={setSearch} placeholder="Filter by seller, client or bill number..." className="mb-4" />

      <DataTable
        columns={columns}
        rows={data?.items ?? []}
        rowKey={(r) => r.id}
        loading={isLoading}
        emptyTitle="No bills waiting"
        emptyDescription="Bills generated by Sellers on the Android app will appear here."
        page={data?.page ?? page}
        pageSize={data?.pageSize ?? 10}
        total={data?.total ?? 0}
        onPageChange={setPage}
        onRowClick={(r) => router.push(`/accounts/bills/${r.id}/invoice`)}
        cardBadge={(r) => <StatusChip status={r.status} />}
      />
    </div>
  );
}
