"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import PageHeader from "@/components/shared/PageHeader";
import SearchBar from "@/components/shared/SearchBar";
import DataTable, { type DataTableColumn } from "@/components/shared/DataTable";
import { StatusChip } from "@/components/shared/StatusChip";
import InvoicePdfLink from "@/components/shared/InvoicePdfLink";
import { listBills } from "@/lib/api/bills";
import type { Bill } from "@/lib/types";
import { cn, formatDate, formatINR, fullName } from "@/lib/utils";

type Tab = "PENDING" | "INVOICED" | "ALL";

const TABS: { value: Tab; label: string }[] = [
  { value: "PENDING", label: "Awaiting invoice" },
  { value: "INVOICED", label: "Invoiced" },
  { value: "ALL", label: "All bills" },
];

export default function BillsInboxPage() {
  const router = useRouter();
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [tab, setTab] = useState<Tab>("PENDING");

  const { data, isLoading, isError, refetch } = useQuery({
    queryKey: ["bills", "inbox", tab, search, page],
    queryFn: () => listBills({ search, page, status: tab === "ALL" ? undefined : tab }),
  });

  const columns: DataTableColumn<Bill>[] = [
    { key: "orderNumber", header: "Order No.", render: (r) => r.order?.orderNumber ?? "—", primary: true },
    { key: "client", header: "Client", render: (r) => (r.client ? fullName(r.client) : "—") },
    { key: "seller", header: "Seller", render: (r) => (r.createdBySeller ? fullName(r.createdBySeller) : "—") },
    { key: "billed", header: "Billed On", render: (r) => formatDate(r.createdAt) },
    {
      key: "invoice",
      header: "Invoice",
      render: (r) =>
        r.invoice ? (
          <div className="flex items-center gap-3">
            <span className="font-semibold text-ink">{r.invoice.invoiceNumber}</span>
            <InvoicePdfLink invoiceId={r.invoice.id} fileName={`${r.invoice.invoiceNumber.replace(/[^A-Za-z0-9._-]/g, "_")}.pdf`} />
          </div>
        ) : (
          <span className="text-rsl-muted">Not invoiced</span>
        ),
    },
    { key: "amount", header: "Amount", render: (r) => formatINR(r.amount), align: "right" },
  ];

  function selectTab(t: Tab) {
    setTab(t);
    setPage(1);
  }

  return (
    <div>
      <PageHeader title="Bills Inbox" description="Every seller's bills. Open a bill awaiting invoice to raise its GST invoice." />

      <div className="mb-3 inline-flex rounded-field border border-rsl-border bg-surface p-1">
        {TABS.map((t) => (
          <button
            key={t.value}
            type="button"
            onClick={() => selectTab(t.value)}
            className={cn(
              "rounded-[8px] px-3.5 py-1.5 text-body font-semibold transition-colors",
              tab === t.value ? "bg-ink text-surface" : "text-rsl-muted hover:text-ink",
            )}
          >
            {t.label}
          </button>
        ))}
      </div>

      <SearchBar
        value={search}
        onChange={(v) => {
          setSearch(v);
          setPage(1);
        }}
        placeholder="Search client, seller or order number..."
        className="mb-4"
      />

      {isError ? (
        <div className="rounded-card border border-rsl-border bg-surface p-6 text-center">
          <p className="font-semibold text-ink">Couldn&apos;t load bills</p>
          <button type="button" onClick={() => refetch()} className="mt-2 text-body font-bold text-rsl-red hover:underline">
            Try again
          </button>
        </div>
      ) : (
        <DataTable
          columns={columns}
          rows={data?.items ?? []}
          rowKey={(r) => r.id}
          loading={isLoading}
          emptyTitle={tab === "INVOICED" ? "No invoiced bills yet" : tab === "PENDING" ? "Nothing waiting for an invoice" : "No bills yet"}
          emptyDescription={
            tab === "PENDING"
              ? "Bills that sellers generate in the Android app appear here until they're invoiced."
              : "Bills generated by sellers in the Android app will appear here."
          }
          page={data?.page ?? page}
          pageSize={data?.pageSize ?? 10}
          total={data?.total ?? 0}
          onPageChange={setPage}
          onRowClick={(r) => router.push(`/accounts/bills/${r.id}/invoice`)}
          cardBadge={(r) => <StatusChip status={r.status} />}
        />
      )}
    </div>
  );
}
